# Custom Language File for Launcher Customizer

[ejs.app]
title = "Azarlya Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.azarlya.com/minecraft/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/z9BJr4eTxs"

[ejs.settings]
sourceGithubLink = "https://github.com/Own0/AzarlyaMCLauncher"
supportLink = "https://www.azarlya.com/minecraft/support/tickets"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Azarlya"
welcomeDescription = "Rejoins-nous sur nos serveurs MMO / Mini-Jeux / Factions Moddé."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de Azarlya."
